/**
 * Mirrors ap_ds_storybook's .storybook/main.js: stories live next to their
 * components, staticDirs serves the generated token CSS so preview.jsx can
 * import it directly.
 */
const config = {
	stories: ["../components/**/*.stories.@(js|jsx)"],
	addons: ["@storybook/addon-a11y", "@storybook/addon-docs"],
	framework: {
		name: "@storybook/react-vite",
		options: {},
	},
	// build/ is regenerated by `npm run build` (build-tokens.js +
	// generate-color-manifest.js) before every `storybook`/`build-storybook`
	// run -- see package.json scripts.
	staticDirs: ["../build"],
};

export default config;
